talent_sites:
  empleosti:
    url: https://empleosti.com.mx/
    queries:
      homepage_enterprise_links: '.enterprise a'
      talent_list_url: '.job-eti a'
      talent_title: ''
      talent_review: ''

  peaku:
    url: https://peaku.co/